config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders do
    resources :order_items
  end

  root to: 'products#index'

  resources :charges
  resources :order_items
  resource :cart, only: [:show]
  resources :books

  resources :products do
    resources :order_items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :update_total
  before_create :update_status
  belongs_to :user

  def calculate_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order, :show_total_items


  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
        Order.new
    end
  end

def show_total_items
  if current_order
    @order_items = current_order.order_items
    quantity_array = []
    @order_items.each do |item|
      quantity_array.push(item.quantity)
    end
    @total_items = quantity_array.sum
  end
end

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
    if current_order
      @amount = (current_order.total_price).to_i
    else
      @amount = 0
    end
  end

  # def create
  #   customer = Stripe::Customer.create(
  #     :email => params[:stripeEmail],
  #     :source  => params[:stripeToken]
  #   )
  #
  #   charge = Stripe::Charge.create(
  #     :customer    => customer.id,
  #     :amount      => @amount,
  #     :description => 'Rails Stripe customer',
  #     :currency    => 'usd'
  #   )
  #   redirect_to root_path
  #   rescue Stripe::CardError => e
  #   flash[:error] = e.message
  #   redirect_to root_path
  #   # end
  # end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
  @amount = (current_order.total_price).to_i

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount * 100,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )
  redirect_to orders_path
  rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to root_path

  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    item_check(item_params)
    @order.save
    session[:order_id] = @order.id
    redirect_to products_path
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    if @order.save
      respond_to do |format|
       format.html { redirect_to cart_path }
       format.js
     end
   else
     render :new
   end
  end

  private

  def item_check(item_params)
    product_id = item_params['product_id'].to_i
    quantity = item_params['quantity'].to_i
    order = OrderItem.all
    if order.exists?(product_id: product_id)
      item = order.where(product_id: product_id)
      item.first.quantity += quantity
      item.first.save
    else
      @order.order_items.new(item_params)
    end
  end

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    if current_user
      @orders = Order.all
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  # def reset_cart
  #   flash[:notice] = "Thanks for placing your order. It is now processing."
  #   order = current_order
  #   order.status = "processing"
  #   order.save
  #   current_order
  # end

private
  def order_params
    params.require(:order).permit(:status, :user_id, :price)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    if current_user
      @order_item = current_order.order_items.new
      @order_items = current_order.order_items
      quantity_array = []
      @order_items.each do |item|
        quantity_array.push(item.quantity)
      end
      @total_items = quantity_array.sum
    end
   end

  def new
    @product = Product.new
    @order_items = current_order.order_items
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      respond_to do |format|
        format.html
        format.js { redirect_to products_path }
      end
    else
      render :new
    end
  end
#   def edit
#   @product = Product.find(params[:id])
# end
#
# def update
#   @order = current_order
#   @product = Product.find(params[:id])
#   @product.update(product_params)
#   if @product.save
#     redirect_to "/orders/#{@order.id}"
#   else
#     flash[:alert] = "There was a problem updating the product"
#     render :edit
#   end
# end

def show
  @order_items = current_order.order_items
end


def destroy
  @product = Product.find(params[:id])
  if @product.destroy
    flash[:notice] = "Product successfully removed!"
    redirect_to products_path
  end
end

private

  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/carts/show.html.erb
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "You sure?", :method => "delete"}%></p>
    <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
  <% end %>
  <p>Your Total: <%= number_to_currency current_order.total_price %></p>
  <p>The Total Items: <%= show_total_items %></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>


<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= number_to_currency current_order.total_price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= number_to_currency @amount %>"
          data-locale="auto"></script>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= number_to_currency @amount%></strong>!</h2>

app/views/charges/new.html.erb
<h1>TEST</h1>
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="my-nav">
      <h1><%= link_to "Store",  products_path %></h1>
      <ul>
        <% if current_user %>
          <li> <%= link_to "Sign out", destroy_user_session_path, method: 'delete' %></li>
          <li><%= link_to cart_path do %>
              Cart (<%= show_total_items %>)
            <% end %></li>

            <li> <%= link_to "View All Products",  products_path %></li>
            <% if current_user.try(:admin?) %>
              <li> <%= link_to "Add New Product",  new_product_path, remote: true %></li>
            <% end %>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
    <div class="container">
    <%= yield %>
    <div id="new-product"></div>
  </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Your orders</h1>

<%  @orders.each do |order| %>
<div class="order">
  <%= order.created_at %><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% order.order_items.each do |item| %>
    <div class="item">
      <%= item.product.name %><br>
      <%= item.quantity %>
    </div>
  <% end %>
</div>
<% end %>

app/views/products/_form.html.erb
<%= render 'layouts/errors', :object => @product %>

<%= form_for @product, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.number_field :price, in: 1.0..20.0, step: 0.01 %>
  <p><%= f.submit %></p>
<% end %>

app/views/products/create.js.erb
$('form').remove();
$('#new-product').show();

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= render "form" %>

app/views/products/index.html.erb
<% @products.each do |product| %>
 <p><%= product.name %> | <%= number_to_currency product.price %>
   <% if current_user %>
     <%= form_for @order_item do |f| %>
       <%= f.hidden_field :product_id, value: product.id %>
       <%= f.number_field :quantity, min: 0 %>
       <%= f.submit "Add to cart" %>
     <% end %></p>
   <% end %>
<% end %>

app/views/products/new.html.erb
<h1>Add a product</h1>

<%= render 'form' %>

app/views/products/new.js.erb
$('#new-product').hide().after('<%= j render("form") %>');